version: '3'
services:

    queue:
        container_name: globomap_loader_queue
        image: rabbitmq:3.7.7
        ports:
            - "${GMAP_QUEUE_PORT}:5672"
            - "${GMAP_QUEUE_ADM_PORT}:15672"
        command: sh -c "rabbitmq-plugins enable rabbitmq_management rabbitmq_shovel rabbitmq_shovel_management; rabbitmq-server"
        volumes:
            - ./scripts/docker/queue/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
            - ./scripts/docker/queue/definitions.json:/etc/rabbitmq/definitions.json:ro
        networks:
            - globomap-api_globomap_net

    api-loader:
        container_name: globomap_loader_api
        build:
            context: ./
            dockerfile: scripts/docker/Dockerfile
        ports:
            - "${GMAP_LOADER_API_PORT}:5000"
            - "${GMAP_LOADER_API_DEBUG_PORT}:5001"
        env_file:
            - ./scripts/docker/globomap.env
        volumes:
            - .:/app
        networks:
            - globomap-api_globomap_net
        external_links:
            - queue:globomap_loader_queue

networks:
    globomap-api_globomap_net:
        external: true

volumes:
    globomap_loader_db_vol:
